spring.application.name=chip-simulator
server.port=8081
# Configuracion de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/chip_simulator?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate / JPA
# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect